# Generated by Django 6.0.2 on 2026-02-15 09:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('course', models.CharField(choices=[('CS', 'Computer Science'), ('IT', 'Information Tech'), ('ME', 'Mechanical'), ('CE', 'Civil')], max_length=2)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='students/')),
                ('age', models.IntegerField()),
                ('joined_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
